### ISSUE TITLE
PINs

### ISSUE THREAD

**Issue by MKleinSB** [joshmarinacci/meowbit-docs#1]
The Pins are the same like the micro:bit Pins. 
https://makecode.microbit.org/device/pins

**Comment by joshmarinacci** [comment]
Yes, I found that I can use the Edge Connector / Pins extension to turn on one of the LEDs. However, the MeowBit docs say there are two LEDs but there aren't two constants. The microbit has a grid of LEDs in the columns (as I see in the specs), but does it also have standalone LEDs?

**Comment by MKleinSB** [comment]
There aren´t any LEDs you can turn on. Only the two on the bottom. The IOBit extension is only for the IO-Bit you can buy. and for the sd-port there exists a bluetooth-card. https://www.igeniusrobot.com/kittenbot_wireless_sd_module__for_meowbit_console_only__wifi_sd_card_game_programming_%E0%B9%80%E0%B8%82%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B9%82%E0%B8%9B%E0%B8%A3%E0%B9%81%E0%B8%81%E0%B8%A3%E0%B8%A1_%E0%B9%82%E0%B8%A3%E0%B8%9A%E0%B8%AD%E0%B8%97_%E0%B9%80%E0%B8%81%E0%B8%A1%E0%B8%AA%E0%B9%8C_%E0%B9%84%E0%B8%A7%E0%B9%84%E0%B8%9F-details.aspx

**Comment by MKleinSB** [comment]
Found the latest Firmware!
http://meowbit-doc.kittenbot.cn/#/more/upgrade
